### ISSUE TITLE
bg_color and txt_color not working in text mode

### ISSUE THREAD

**Issue by cderv** [gesquive/slate#2]
Hi, 

When I use image mode (providing img in `links.yml`), background color is working. However, in text mode (not providing any img link), `bg_color` & `txt_color` are not working. 

Not sure where to search for a solution. Will try to understand how your theme work but if you any idea...

**Comment by cderv** [comment]
It seems to be different behavior on different navigator (IE, firefox). Something to do with the slate.js script which use those attributes. I may miss something

**Comment by cderv** [comment]
On Firefox, here is what I have when I am not providing an img to google music 

```yaml
-
  name: "google music"
  url: "https://play.google.com/music/listen"
  bg_color: "#ffffff"
  txt_color: "#ff5722"
  tags: ["music"]
```

![capture](https://cloud.githubusercontent.com/assets/6791940/26557066/f99d7072-449e-11e7-93fe-eb54de730efa.png)

Is there a problem with my version of Firefox or with the `slate.js` file ?
